version: '3.8'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd react-app && yarn start"
    ports:
      - "3000:3000"